### ISSUE TITLE
label for assert_matches

### ISSUE THREAD

**Issue by KenKundert** [asottile/re-assert#119]
I tend to use re-assert with pytest.  One issue with pytest is that if you have asserts in loops it can be difficult to identify the failing case.  This tends to come up often with parametrized tests. I tend to handle this situation by adding an identifier to each case, and passing that identifier to the assert statement so that when it fails I can easily identify the case that fails.  This is not an option with re-assert.

Do you think it would be a good idea to allow the user to specify an identifier to the constructor and include that identifier in self._fail?

```
>>> Matches('foo', id="alpha").assert_matches('food')
>>> Matches('foo', id='beta').assert_matches('fork')
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/asottile/workspace/re-assert/re_assert.py", line 63, in assert_matches
    assert self == s, self._fail
AssertionError:  beta: regex failed to match at:
> fork
  ^
```

**Comment by asottile** [comment]
don't write asserts in loops. use parametrize

**Comment by KenKundert** [comment]
I am using parametrize.  Specifically, I am using [Parametrize From File](https://pypi.org/project/parametrize-from-file/).

My tests are naturally organized into several levels.  *Parameterize From File* nicely handles the first level, but the lower levels need to be handled by looping within the test function.  It is in this situation where adding a label to Matches would be helpful.

**Comment by asottile** [comment]
seems self inflicted -- you're free to fork, subclass, write a wrapper function etc. but I don't see universal value in adding and maintaining forever the functionality you're describing which seems to have little value for most consumers

**Comment by asottile** [comment]
unrelated, and as a pytest maintainer, parametrize-from-file seems like a bad idea -- kinda the point of parametrize is that the cases are close to the test so they're obvious to the test reader.  I don't have to go hunting in an external file to figure out what's being tested

**Comment by RonnyPfannschmidt** [comment]
Subtest can be used to get the labels op wants

**Comment by KenKundert** [comment]
Subtest looks very promising.  Thank you for that suggestion.

I disagree with your assessment of parametrize-from-file.  I love it.  It makes the specifying tests and expected results much easier and more natural.  parametrize-from-file paired with NestedText is especially nice. NestedText requires no quoting or escaping, so the specification of regular expressions is especially clean.  My experience is that once the test methodology is set, I rarely open the Python test file.  I just interact with the NestedText file. Splitting the tests from the test code really simplifies the addition and maintenance of tests.
