### ISSUE TITLE
Expose type hints

### ISSUE THREAD

**Issue by Dreamsorcerer** [asottile/re-assert#137]
Can we get the typing information exposed for type checkers (i.e. adding a py.typed file)?

**Comment by asottile** [comment]
nope!  py.typed doesn't support single-file distributions

**Comment by Dreamsorcerer** [comment]
> The single-file module should be refactored into a package and indicate that the package supports typing as described above.
https://typing.readthedocs.io/en/latest/spec/distributing.html#packaging-typed-libraries

That's a bit awkward..

**Comment by asottile** [comment]
> should be refactored into a package

yeah nope not happening
