### ISSUE TITLE
Support Convenience Function `re.fullmatch()`

### ISSUE THREAD

**Issue by backbord** [asottile/re-assert#46]
Hi,

I really like this project!
However, I would love to be able to call `Matches.assert_fullmatch(s: str)`.

Do you think, it would be possible to add such a convenience method? Perhaps by using `re.fullmatch()` or by checking against the original pattern wrapped in `\A(...)\Z`?

Thanks and best regards,
Tim

**Comment by asottile** [comment]
that might be possible, but it probably works already to just use `Matches(r'\A...\Z')` with your existing pattern?

but actually `fullmatch` doesn't mean `\A...\Z` -- I think it really just means `...\Z` (and the left must be the current position (but possibly offset))

```pycon
>>> import re
>>> re.compile(f'f+')
re.compile('f+')
>>> reg = re.compile(f'f+')
>>> reg.fullmatch('affff', 1)
<re.Match object; span=(1, 5), match='ffff'>
>>> reg2 = re.compile(r'\Af+\Z')
>>> reg2.fullmatch('affff', 1)
>>> 
```

looking at the code I don't think it's easy to shim this in -- it's probably best to just use `\Z` or `$` in your test pattern directly?

**Comment by backbord** [comment]
Hi Anthony,

In the project I'm working on, we have re-assert in a function that is used by multiple test modules which do not know about re-assert and just expect `re.fullmatch()` behaviour for a regex they present.
As a workaround we've implemented a wrapper for their regex as `Matches(rf"\A(?:{regex})\Z")`, since their regex could be a top-level union like `r"a|b"`.

Regarding the question whether to begin at `\A` or the (offset) current position: I'm not too familiar with the internals of the regex matching algorithm and don't know cases where the left would be offset, but the [docs](https://docs.python.org/3/library/re.html#re.fullmatch) say 
> If the whole string matches the regular expression pattern, [...]

However, I fully agree: I don't see fullmatch being an easy addition to the underlying code.

Sorry for the late reply.
Thanks for the help and best regards,
Tim
